spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RoleSECURITY
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update


    properties:
      hibernate:
      database: mysql
      show-sql: true